### ISSUE TITLE
Module does not work for Magento 2.2.8

### ISSUE THREAD

**Issue by PascalBrouwers** [kiwicommerce/magento2-enhanced-smtp#2]
### Preconditions

1. Magento 2.2.8

### Steps to reproduce

1. Create an order and let Magento run the cron to send order emails

### Expected result

1. Should not give an error and send the email.

### Actual result

1. ```Error when running a cron job at vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:324, Error(code: 0): Call to undefined method Magento\\Framework\\Mail\\Message::getRecipients() at vendor/kiwicommerce/module-enhanced-smtp/Email/Log/SaveEmailLog.php:280```

**Comment by PascalBrouwers** [comment]
Seems like allot of the implementation does not work. You'll get the same error for `$this->message->getHeaders()`, etc.

**Comment by kiwi-commerce** [comment]
Hi @PascalBrouwers . Thank you for your report.
The issue has been fixed.

Related commit(s):
[532dba75e4549875ddf3e5a9e03a4aa70116b856](https://github.com/kiwicommerce/magento2-enhanced-smtp/commit/532dba75e4549875ddf3e5a9e03a4aa70116b856)

**Comment by PascalBrouwers** [comment]
Still not working, now I get: "Zend\Mail\Transport\Smtp transport expects either a Sender or at least one From address in the Message; none provided"

**Comment by kiwi-commerce** [comment]
Hello @PascalBrouwers 
This issue is the core issue that reported in the Magento https://github.com/magento/magento2/issues/14952

**Comment by PascalBrouwers** [comment]
ok, tnx
